"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import logging
from django.core.exceptions import ImproperlyConfigured

# [FASE 6 §6.2] Sentry — inicializar antes que otros imports para capturar errores tempranos
SENTRY_DSN = os.environ.get('SENTRY_DSN')
if SENTRY_DSN and os.environ.get('DEBUG', 'False') == 'False':
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration

    def _scrub_pii(event, hint=None):
        """Elimina headers sensibles antes de enviar a Sentry (RGPD)."""
        if 'request' in event:
            headers = event['request'].get('headers', {})
            for h in ['Authorization', 'Cookie', 'X-Api-Key']:
                headers.pop(h, None)
        return event

    sentry_logging = LoggingIntegration(
        level=logging.INFO,
        event_level=logging.ERROR,
    )

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            sentry_logging,
        ],
        environment=os.environ.get('SENTRY_ENV', 'production'),
        release=os.environ.get('RENDER_GIT_COMMIT', 'unknown')[:7],
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        profiles_sample_rate=0.1,
        send_default_pii=False,
        before_send=_scrub_pii,
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key-not-for-production'
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set in production")

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
if not ALLOWED_HOSTS:
    if DEBUG:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*.localhost']
    else:
        raise ImproperlyConfigured("ALLOWED_HOSTS must be set in production")

# CSRF trusted origins — must include frontend domains for cross-origin POST
CSRF_TRUSTED_ORIGENS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGENS', '').split(',') if o.strip()]
if not CSRF_TRUSTED_ORIGENS and DEBUG:
    CSRF_TRUSTED_ORIGENS = ['http://localhost:5173', 'http://127.0.0.1:5173']

# Cache configuration for rate limiting and session management
# Uses Redis in production (REDIS_URL env var); falls back to LocMemCache in development
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'gestion-saude',
            'TIMEOUT': 300,
        }
    }
elif not DEBUG:
    raise ImproperlyConfigured("REDIS_URL must be set in production for cache backend")
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'belkis-saude-cache',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000
            }
        }
    }


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Nuevas apps de terceros
    'rest_framework',          # Django REST Framework
    'corsheaders',             # Para manejar CORS
    'usuarios',
    'notificaciones',
    'dbbackup',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe ir antes de CommonMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve media files in production
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# WhiteNoise configuration for serving media files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_CACHE = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Frontend servido como Static Site separado (§2.4)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASE_URL_CONFIG = os.environ.get('DATABASE_URL')
if DATABASE_URL_CONFIG:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL_CONFIG,
            conn_max_age=600,
            ssl_require=True
        )
    }
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True
    DATABASES['default']['OPTIONS'] = DATABASES['default'].get('OPTIONS', {})
    DATABASES['default']['OPTIONS']['connect_timeout'] = 10
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded images) — separated from frontend build (§2.4)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Ensure media directories exist
import os
try:
    os.makedirs(str(MEDIA_ROOT), exist_ok=True)
    os.makedirs(str(MEDIA_ROOT / 'perfiles'), exist_ok=True)
except Exception as e:
    print(f"Warning: Could not create media directories: {e}")

# [FASE 7 §7.4] Storage backend con feature flag
# Si MEDIA_STORAGE=s3, usa S3 (Cloudflare R2/Supabase Storage/AWS S3)
# Si no, usa FileSystemStorage (default, para dev)
# VER NOTA: django-storages y boto3 están en requirements.txt como comentados;
# instalar con: pip install django-storages[s3] boto3
if os.environ.get('MEDIA_STORAGE') == 's3':
    try:
        STORAGES = {
            'default': {
                'BACKEND': 'storages.backends.s3.S3Storage',
                'OPTIONS': {
                    'access_key': os.environ.get('AWS_ACCESS_KEY_ID'),
                    'secret_key': os.environ.get('AWS_SECRET_ACCESS_KEY'),
                    'bucket_name': os.environ.get('AWS_STORAGE_BUCKET_NAME'),
                    'endpoint_url': os.environ.get('AWS_S3_ENDPOINT_URL'),
                    'region_name': os.environ.get('AWS_S3_REGION_NAME', 'auto'),
                    'default_acl': None,
                    'querystring_auth': True,
                    'file_overwrite': False,
                    'object_parameters': {'CacheControl': 'max-age=86400'},
                },
            },
            'staticfiles': {
                'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
            },
        }
    except ImportError:
        print('[FASE 7 §7.4] django-storages no instalado; usando FileSystemStorage')
        STORAGES = {
            'default': {
                'BACKEND': 'django.core.files.storage.FileSystemStorage',
            },
            'staticfiles': {
                'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
            },
        }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }


# CORS configuration — origins driven by env var CORS_ALLOWED_ORIGINS (comma-separated)
_default_cors_origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:5175",
    "http://127.0.0.1:5175",
]
_env_cors = [o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]
CORS_ALLOWED_ORIGENS = _env_cors if _env_cors else _default_cors_origins

# Si hay credenciales permitidas, los hosts permitidos deben coincidir
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_EXPOSE_HEADERS = ["Content-Type", "Authorization"]
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_PREFLIGHT_THRESHOLD = 86400


# Al final de settings.py, después de todo
AUTH_USER_MODEL = 'usuarios.Usuario'



# Configuración de Django REST Framework - VERSIÓN ACTUALIZADA CON JWT
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT primero
        'rest_framework.authentication.SessionAuthentication',  # Para probar en navegador
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # Rate limiting configuration
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '60/minute',  # Rate limit for authenticated users
        'anon': '30/minute',  # Rate limit for anonymous users
        'registro': '5/minute',  # Dedicated rate limit for public registration
    }
}



# Configuración de email (opcional)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# [FASE 5 §5.3] Email backend: Resend/anymail si está configurado, console en dev
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')

if RESEND_API_KEY:
    EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
    ANYMAIL = {
        'RESEND_API_KEY': RESEND_API_KEY,
    }
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    if not DEBUG:
        logging.warning("[FASE 5 §5.3] Email: fallback a console backend (sin RESEND_API_KEY en prod)")

# [FASE 5 §5.2] Limitar tamaño de uploads en memoria
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Configuración de Twilio (opcional)
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_NUMBER = os.getenv('TWILIO_WHATSAPP_NUMBER', '')

# Configuración de JWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Token dura 60 minutos
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Refresh token dura 1 día
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,  # Usa la misma clave secreta de Django
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Security settings for production (HTTPS / HSTS / secure cookies)
# Only activated when DEBUG=False so local dev over HTTP is unaffected
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# [FASE 6 §6.3] Logging estructurado: JSON en prod, texto legible en dev
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s',
        },
        'verbose': {
            'format': '{levelname} {asctime} {name} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if DEBUG else 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django.request': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'django.security': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'chatia.metrics': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'notificaciones.services': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}
