# Generated by Django 6.0.2 on 2026-10-04 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notificaciones", "0003_notificacion_intentos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["usuario", "leida"], name="notif_usuario_leida_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["usuario", "estado"], name="notif_usuario_estado_idx"
            ),
        ),
    ]
