# Generated by Django 6.0.2 on 2026-10-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_report_admin_superusers"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="horario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hora_fin__lte", models.F("hora_inicio")), _negated=True
                ),
                name="horario_hora_fin_mayor_inicio",
            ),
        ),
    ]
