# Generated by Django 6.0.2 on 2026-10-04 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_horario_check_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="duracion_minutos",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Duración de la cita. Default: 30 minutos.",
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(240),
                ],
                verbose_name="Duración en minutos",
            ),
        ),
    ]
