# Generated by Django 6.0.2 on 2026-10-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0007_cita_duracion_minutos"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cita",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="cita",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "cancelada"), _negated=True),
                fields=("doctor", "fecha", "hora"),
                name="cita_unique_activa",
            ),
        ),
    ]
