# Generated by Django 6.0.2 on 2026-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("usuarios", "0008_cita_unique_constraint_condicional"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cita",
            index=models.Index(
                fields=["doctor", "fecha", "estado"], name="cita_doc_fecha_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cita",
            index=models.Index(
                fields=["paciente", "fecha"], name="cita_paciente_fecha_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horario",
            index=models.Index(
                fields=["doctor", "dia_semana", "activo"],
                name="horario_doc_dia_activo_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["rol"], name="usuario_rol_idx"),
        ),
    ]
